### ISSUE TITLE
In-Store Solution 

### ISSUE THREAD

**Issue by Ryan-Lee-Birl** [wearebirl/wearebirl#26]
## Features :computer:

- [x] #42
- [x] #43
- [x] #45
- [x] #46
- [ ] Credit Boost- No Change Needed?
- [ ] Condition Select 
- [ ] Customer Information
- [ ] Return Handling
- [ ] POS Voucher Generation
- [ ] Non-POS Process
- [ ] Create in-store user accounts
- [ ] Management App Changes
- [ ] #35

**Comment by peter-birl** [comment]
@edday57 - Do you think we can have a working version of this ready by 13th January? We have a brand meeting then and I can get their feedback. We can catch up on 6th Jan.

**Comment by peter-birl** [comment]
In-Store Solution Updates

- [ ] 
- [ ] Can we change terminology of Stores to Organizations?
- [ ] Then we can call Outlets Stores?
- [ ] Please re-name Process Return to Generate Postage Label
- [ ] Shall we move Delete Outlet away from the top so it doesn't get clicked accidentally?
- [ ] On the postage label page, please update to Process your Trade-ins
- [ ] Copy underneath to read – Please assign the trade-ins you will be sending in this parcel below. Please note that you can add  a maximum of 10kg per parcel.
